use_frameworks!

platform :ios, '9.0'

target 'M7SafeObject_Example' do
  pod 'M7SafeObject', :path => '../'

  target 'M7SafeObject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
